# Generated by Django 5.2.7 on 2025-11-03 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_search_vector_alter_document_title_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='doc_fts_gin',
        ),
        migrations.RemoveField(
            model_name='document',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
